//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CronEspresso.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CronEspresso.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cron expression entered was an empty string, please supply a string for validation.
        /// </summary>
        public static string EmptyString {
            get {
                return ResourceManager.GetString("EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cron expression entered is not in a correct cron format. The correct format is 6 (or 7 if you included the year values) values sperated by a single space character (e.g. &quot;* * * * ? *&quot;). The value provided was &apos;{0}&apos;.
        /// </summary>
        public static string InvalidCronFormat {
            get {
                return ResourceManager.GetString("InvalidCronFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The day of month value is invalid. Allowed values are &quot;1 to 31 , - * ? / L W&quot;. The value provided was &apos;{0}&apos;.
        /// </summary>
        public static string InvalidDayOfMonth {
            get {
                return ResourceManager.GetString("InvalidDayOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The day of week value is invalid. Allowed values are &quot;1 to 7 SUN to SAT , - * ? / L #&quot;. The value provided was &apos;{0}&apos;.
        /// </summary>
        public static string InvalidDayOfWeek {
            get {
                return ResourceManager.GetString("InvalidDayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hour value is invalid. Allowed values are &quot;0 to 24 , - * /&quot;. The value provided was &apos;{0}&apos;.
        /// </summary>
        public static string InvalidHoursValue {
            get {
                return ResourceManager.GetString("InvalidHoursValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minute value is invalid. Allowed values are &quot;0 to 59 , - * /&quot;. The value provided was &apos;{0}&apos;.
        /// </summary>
        public static string InvalidMinutesValue {
            get {
                return ResourceManager.GetString("InvalidMinutesValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The month value is invalid. Allowed values are &quot;1 to 12 JAN to DEC , - * /&quot;. The value provided was &apos;{0}&apos;.
        /// </summary>
        public static string InvalidMonth {
            get {
                return ResourceManager.GetString("InvalidMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The seconds value is invalid. Allowed values are &quot;0 to 59 , - * /&quot;. The value provided was &apos;{0}&apos;.
        /// </summary>
        public static string InvalidSecondsValue {
            get {
                return ResourceManager.GetString("InvalidSecondsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The year value is invalid. Allowed values are &quot;empty 1970-2099 , - * /&quot;. The value provided was &apos;{0}&apos;.
        /// </summary>
        public static string InvalidYear {
            get {
                return ResourceManager.GetString("InvalidYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cron format provided &apos;{0}&apos; is a valid cron expression.
        /// </summary>
        public static string ValidExpression {
            get {
                return ResourceManager.GetString("ValidExpression", resourceCulture);
            }
        }
    }
}
